import { BriefingData } from '../types';
import { generateBriefingPDF } from './pdfGenerator';

/**
 * Sends a SalesScout AI Briefing email using Google Gmail API directly from the browser.
 */
export async function sendBriefingEmailViaGmail(
  accessToken: string,
  recipientEmail: string | string[],
  briefing: BriefingData,
  customNote?: string
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const pdfDoc = generateBriefingPDF(briefing);
    const pdfArrayBuffer = pdfDoc.output('arraybuffer');
    
    // Convert ArrayBuffer to base64 string
    const bytes = new Uint8Array(pdfArrayBuffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    const pdfBase64 = btoa(binary);

    const pdfFileName = `SalesScout_Briefing_${briefing.companyName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    const subject = `[SalesScout AI] Executive Briefing: ${briefing.companyName}${briefing.stakeholderName ? ` / ${briefing.stakeholderName}` : ''}`;

    const toHeader = Array.isArray(recipientEmail) ? recipientEmail.join(', ') : recipientEmail;

    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; color: #0B1F3A; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #E2E8F0; border-radius: 12px;">
        <div style="background-color: #0B1F3A; color: white; padding: 16px; border-radius: 8px 8px 0 0; text-align: center;">
          <h2 style="margin: 0; font-size: 20px;">SalesScout <span style="color: #1FA9A0;">AI</span></h2>
          <p style="margin: 4px 0 0 0; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #94A3B8;">Walk in informed. Every time.</p>
        </div>

        <div style="padding: 20px; background-color: #FFFFFF;">
          <p style="font-size: 14px; color: #334155;">Hello,</p>
          <p style="font-size: 14px; color: #334155; line-height: 1.5;">
            Here is your requested <strong>Pre-Meeting Executive Briefing</strong> for <strong>${briefing.companyName}</strong>${briefing.stakeholderName ? ` (${briefing.stakeholderName} - ${briefing.stakeholderTitle || 'Executive'})` : ''}.
          </p>

          ${customNote ? `
            <div style="background-color: #F8FAFC; border-left: 4px solid #1FA9A0; padding: 12px; margin: 16px 0; font-size: 13px; color: #1E293B;">
              <strong>Note from Rep:</strong> ${customNote}
            </div>
          ` : ''}

          <div style="background-color: #F8F9FA; border: 1px solid #E2E8F0; border-radius: 8px; padding: 16px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #0B1F3A; font-size: 15px;">Executive Key Takeaways</h3>
            <ul style="padding-left: 20px; margin-bottom: 0; font-size: 13px; color: #475569;">
              <li><strong>Industry:</strong> ${briefing.companySnapshot.industry}</li>
              <li><strong>HQ / Funding:</strong> ${briefing.companySnapshot.hqLocation} | ${briefing.companySnapshot.fundingOrRevenue}</li>
              <li><strong>Why It Matters Now:</strong> ${briefing.companySnapshot.whyItMattersNow}</li>
              ${briefing.stakeholderProfile ? `<li><strong>Stakeholder Style:</strong> ${briefing.stakeholderProfile.communicationStyle}</li>` : ''}
            </ul>
          </div>

          <p style="font-size: 13px; color: #64748B;">
            📄 <em>The full structured PDF report is attached to this email for quick reading or offline review before your call.</em>
          </p>
        </div>

        <div style="text-align: center; padding-top: 16px; border-top: 1px solid #E2E8F0; font-size: 11px; color: #94A3B8;">
          Generated by SalesScout AI • AI-synthesized intelligence — verify key facts prior to high-stakes meetings.
        </div>
      </div>
    `;

    const boundary = "===SalesScoutBoundary" + Date.now().toString(16) + "===";
    
    let rawMime = `To: ${toHeader}\r\n`;
    rawMime += `Subject: ${subject}\r\n`;
    rawMime += `MIME-Version: 1.0\r\n`;
    rawMime += `Content-Type: multipart/mixed; boundary="${boundary}"\r\n\r\n`;

    // Part 1: HTML Body
    rawMime += `--${boundary}\r\n`;
    rawMime += `Content-Type: text/html; charset=UTF-8\r\n`;
    rawMime += `Content-Transfer-Encoding: 7bit\r\n\r\n`;
    rawMime += `${bodyHtml}\r\n\r\n`;

    // Part 2: PDF Attachment
    rawMime += `--${boundary}\r\n`;
    rawMime += `Content-Type: application/pdf; name="${pdfFileName}"\r\n`;
    rawMime += `Content-Disposition: attachment; filename="${pdfFileName}"\r\n`;
    rawMime += `Content-Transfer-Encoding: base64\r\n\r\n`;
    rawMime += `${pdfBase64}\r\n\r\n`;

    rawMime += `--${boundary}--`;

    // Base64URL encode the MIME string
    const base64UrlRaw = btoa(unescape(encodeURIComponent(rawMime)))
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

    const res = await fetch('https://www.googleapis.com/gmail/v3/users/me/messages/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        raw: base64UrlRaw,
      }),
    });

    if (!res.ok) {
      const errJson = await res.json().catch(() => ({}));
      throw new Error(errJson.error?.message || `Gmail API HTTP error ${res.status}`);
    }

    const data = await res.json();
    return { success: true, messageId: data.id };
  } catch (err: any) {
    console.error('Error sending briefing email via Gmail API:', err);
    return { success: false, error: err.message || 'Failed to send email via Gmail API' };
  }
}
